### ISSUE TITLE
Custom groups based on additional columns in the input file

### ISSUE THREAD

**Issue by AjayOza** [thlytras/MOMOpack-for-R#1]
If you have another field in the mortality input file as well as age, such as Hospital or Gender, then greating a group based on this is not a simple as in the original A-MOMO package. Ideally one should only have to declare the MOMOMaster.R file (plus the models used for each group). Does it require changes to makeMOMO.R file too and perhaps elsewhere?

**Comment by thlytras** [comment]
Actually, IMHO it's simpler! ;-)
And you don't need to modify anything other than MOMOmaster.R .

The groups are defined in a named R list of strings or NAs (MOMOgroups) and the corresponding models in a similarly named character vector (MOMOmodels). These are then given as arguments to makeMOMOinput(), together with the deaths data.frame and every other parameters. In makeMOMOinput() the strings in MOMOgroups are evaluated against the deaths data.frame using eval() (lines 53-60 in /code/makeMOMOinput.R), and group variables are constructed (as a logical vector in the input data.frame). If the list element is not a string but NA, then the corresponding column name is itself interpreted as the grouping variable in the data.frame.

Thus you actually have two ways of defining groups in your input data.frame, by setting up appropriate named elements in the MOMOgroups list:
(1) Either you supply an expression, as a character string, creating the group on-the-fly; you can use _any_ variable that exists in your input data.frame, not just age.
(2) Or you supply NA, and then the element name is interpreted as the group variable in the input data.frame (which you must have created beforehand).

Please tell me if anything is not clear, and then I can close this issue...

**Comment by AjayOza** [comment]
OK - I'll try that again. Please go ahead and close this issue.
